### ISSUE TITLE
Level-Up

### ISSUE THREAD

**Issue by DeathsGun** [VillageTeam/Time-of-Kings#1]
Hey, in der Distributor.java wird mir  `wood.add(sawmill.collect());
                      costs = sawmill.levelUp(resources);
                      break;` als Fehler angezeigt

**Comment by SupressWarnings** [comment]
Was denn für ein Fehler? Kennt er sawmill nicht? Oder die Methoden? Mit "Fehler" kann ich leider nichts anfangen, danke das du wenigstens schonmal gesagt hast WO der Fehler liegt, nur da der Code bei mir läuft ist mir leider nicht klar WAS der Fehler ist.

**Comment by DeathsGun** [comment]
Welche IDE benutz du eigentlich ?

**Comment by SupressWarnings** [comment]
Ich benutze Eclipse. Warum?

**Comment by DeathsGun** [comment]
Weil bei mir in Eclipse die Fehler angezeigt werden

**Comment by SupressWarnings** [comment]
Ja, welche Fehler denn?

**Comment by SupressWarnings** [comment]
Werden dir alle drei Zeilen als Fehler angezeigt oder nur eine? welche Methode kann er genau nicht finden? Sie sollten eigentlich alle vorhanden sein, so wie es aussieht. Außerdem müsste ja dann jedes Gebäude der Level-Up Funktion rummeckern, nicht nur das eine. Meckern alle rum und welche Methode felhlt GENAU?

**Comment by DeathsGun** [comment]
Warte mache gleich Screen

**Comment by DeathsGun** [comment]
<img width="707" alt="1" src="https://cloud.githubusercontent.com/assets/13536793/16388981/0c32b9c4-3c9c-11e6-8fae-25c959778bec.png">
<img width="757" alt="2" src="https://cloud.githubusercontent.com/assets/13536793/16388982/0c5addfa-3c9c-11e6-8e14-e1df3156cdf9.png">

Fehlermeldung:
The method levelUp(int, int, int) in the type Building is not applicable for the arguments (int[])  Distributor.java

**Comment by SupressWarnings** [comment]
Sollte jetzt gefixt sein

**Comment by DeathsGun** [comment]
jep
