### ISSUE TITLE
DeathLib

### ISSUE THREAD

**Issue by SupressWarnings** [VillageTeam/Time-of-Kings#2]
@DeathsGun Was ist die in der Version 0.4 angesprochene DeathLib? Wo ist der Code dazu? Wann genau verwendest du die?

**Comment by DeathsGun** [comment]
Werde den Source Code gleich veröffentlichen dort sind die ganzen util Klassen und ein paar Extras eingebaut

**Comment by SupressWarnings** [comment]
Wo bleibt denn jetzt der Sourcecode?

**Comment by DeathsGun** [comment]
Ich hab im Moment keine Zeit da ich Arbeiten muss

**Comment by DeathsGun** [comment]
@SupressWarnings Erster Source code draußen
