### ISSUE TITLE
Kleines nettes Feature

### ISSUE THREAD

**Issue by DeathsGun** [VillageTeam/Time-of-Kings#3]
Ich habe ein bisschen gebastelt und folgendes hinbekommen: 
![deinewerte](https://cloud.githubusercontent.com/assets/13536793/16897122/46baec40-4ba8-11e6-9cd6-395b0671883e.png)

Meine Frage ist jetzt soll ich es einbauen ?

**Comment by SupressWarnings** [comment]
@DeathsGun ich bin gerade dabei, bei der Überarbeitung des Codes eine GUI zu erstellen, es wäre also erstmal nicht nötig. Es wäre trotzdem vielleicht mal interessant, wenn du den Sourcecode zeigst, den könnte ich verwenden.

**Comment by DeathsGun** [comment]
es ist aber keine Java-GUI sondern eine Website im Browser

**Comment by DeathsGun** [comment]
@SupressWarnings 
[ToK.zip](https://github.com/ToK-Gameteam/Time-of-Kings/files/367827/ToK.zip)

**Comment by Cromewell** [comment]
@SupressWarnings Welches Framework benutzt du für die GUI? Wenn es JavaFX ist könnte ich behilflich sein :D

**Comment by DeathsGun** [comment]
@SupressWarnings  das ist html xD und wenn ich eine GUI programmiere benutze ich swing

**Comment by DeathsGun** [comment]
xD

**Comment by Cromewell** [comment]
@DeathsGun 

>  das ist html xD

Du hast es zwar nicht an mich adressiert, aber ich glaube, du meintest mich: ich meinte mit meinem Kommentar aber die von SupressWarnings erwähnte GUI, an der er arbeitet :P

**Comment by DeathsGun** [comment]
@Cromewell egal

**Comment by SupressWarnings** [comment]
@DeathsGun, @Cromewell Ich habe noch nicht viel von der Gui gemacht und gucke noch, derzeitig bin ich nicht da und arbeite, wie ihr vielleicht gesehen habt an einem anderen Projekt.

**Comment by SupressWarnings** [comment]
@DeathsGun wo wir hier gerade bei neuen features sind, es wäre schön, wenn du deine Veränderungen am Spiel auch posten würdest. Ich würde es schon gerne sehen, wenn du z. B. die DeathLib einbaust oder so. Du kannst dir ja auch deine eigene Branch erstellen.

**Comment by DeathsGun** [comment]
@SupressWarnings  ok bin aber grad im urlaub

**Comment by SupressWarnings** [comment]
@DeathsGun ok ich hab mich übrigens für JavaFX entschieden.
